import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import { PropsWithChildren } from "react";
import "./globals.css";
import Link from "next/link";
import { NAV_LINKS } from "@/src/config";
import { cn } from "@/src/lib/utils";
import Navbar from "../components/Navbar";

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }: PropsWithChildren & { modal: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", figtree.variable)}
    >
      <body className="min-h-full flex flex-col">
      <div>
        <Navbar />
        <main className="py-16 max-w-4xl mx-auto">{children}</main>
        {modal}
      </div>
      </body>
    </html>
  );
}
